### ISSUE TITLE
Remaining failures in Windows

### ISSUE THREAD

**Issue by eregon** [ruby/spec#230]
The number of errors+failures in Windows is now only 24! https://ci.appveyor.com/project/eregon/spec/build/140

However, these ones seem non-trivial to fix. Some of them might be just not applicable on Windows, but most of these seem to be inconsistent with the behavior on UNIX-like platforms. Some of them are also worth to write a MRI bug.

Examples can be skipped on Windows using `platform_is_not :windows`,
but then the behavior on Windows should also be specified in a `platform_is :windows`. If the behavior is strange, it's worth a MRI bug/issue to ask if this is intentional/Windows limitation/actual bug.

@vais @nobu Could I ask for your help to identify which failures/errors fall in which category and to get down to 0 failures/errors but still report bad behavior on MRI's bug tracker?

**Comment by eregon** [comment]
Here are my thoughts after analyzing some of them:
```
1)
File.chown raises an error for a non existent path FAILED
Expected Errno::ENOENT but no exception was raised (1 was returned)
C:/projects/spec/core/file/chown_spec.rb:68:in `block (2 levels) in <top (required)>'
C:/projects/spec/core/file/chown_spec.rb:3:in `<top (required)>'
 ```

So File.chown("not_existent_path") just returns 1 on Windows ??

```
2)
File.new opens the existing file, does not change permissions even when they are specified FAILED
Expected "100444"
 to equal "100644"
C:/projects/spec/core/file/new_spec.rb:64:in `block (2 levels) in <top (required)>'
C:/projects/spec/core/file/new_spec.rb:4:in `<top (required)>'
 
3)
File.new can't alter mode or permissions when opening a file FAILED
Expected Errno::EINVAL but no exception was raised (false was returned)
C:/projects/spec/core/file/new_spec.rb:148:in `block (2 levels) in <top (required)>'
C:/projects/spec/core/file/new_spec.rb:4:in `<top (required)>'
 
4)
File.open opens the existing file, does not change permissions even when they are specified FAILED
Expected "100444"
 to equal "100644"
C:/projects/spec/core/file/open_spec.rb:143:in `block (2 levels) in <top (required)>'
C:/projects/spec/core/file/open_spec.rb:7:in `<top (required)>'
```

So UNIX does not care about extra permissions args for existent files to `File#open/new` but Windows does?

```
5)
File::Stat#<=> is able to compare files by the same modification times ERROR
Errno::EACCES: Permission denied @ utime_failed - C:/projects/spec/rubyspec_temp/205-i_exist
C:/projects/spec/core/file/stat/comparison_spec.rb:19:in `utime'
C:/projects/spec/core/file/stat/comparison_spec.rb:19:in `block (2 levels) in <top (required)>'
C:/projects/spec/core/file/stat/comparison_spec.rb:3:in `<top (required)>'
...
```
Why does this fail? `File.utime` does not work on Windows? Does it need special permissions?

```
8)
File::Stat#inspect produces a nicely formatted description of a File::Stat object FAILED
Expected "#<File::Stat dev=0x2, ino=0, mode=0100644, nlink=1, uid=0, gid=0, rdev=0x2, size=8, blksize=nil, blocks=nil, atime=2016-04-06 13:16:29 +0000, mtime=2016-04-06 13:16:29 +0000, ctime=2016-04-06 13:16:29 +0000>"
to equal "#<File::Stat dev=0x2, ino=0, mode=0100644, nlink=1, uid=0, gid=0, rdev=0x2, size=8, blksize=nil, blocks=nil, atime=2016-04-06 13:16:29 +0000, mtime=2016-04-06 13:16:29 +0000, ctime=2016-04-06 13:16:29 +0000, birthtime=2016-04-06 13:16:29 +0000>"
 
C:/projects/spec/core/file/stat/inspect_spec.rb:27:in `block (4 levels) in <top (required)>'
C:/projects/spec/core/file/stat/inspect_spec.rb:3:in `<top (required)>'
```
`birthtime` is missing from the output. Bug (in MRI or the spec) or some Windows do not have birthtime?

```
9)
File::Stat#nlink returns the number of links to a file FAILED
Expected 1
 to equal 2
 
C:/projects/spec/core/file/stat/nlink_spec.rb:17:in `block (2 levels) in <top (required)>'
C:/projects/spec/core/file/stat/nlink_spec.rb:3:in `<top (required)>'
```
Is nlink bugged on Windows? The documentation I found seemed to indicate it does actually report the number of (hard) links.

```
10)
IO.copy_stream from an IO does not change the IO offset when an offset is specified ERROR
NotImplementedError: pread() not implemented
C:/projects/spec/core/io/copy_stream_spec.rb:134:in `copy_stream'
C:/projects/spec/core/io/copy_stream_spec.rb:134:in `block (3 levels) in <top (required)>'
C:/projects/spec/core/io/copy_stream_spec.rb:93:in `<top (required)>'
...
```
Seems the wrong error, worth a MRI bug report I think.
```
14)
IO.popen does not throw an exception if child exited and has been waited for FAILED
Expected 0 to be nil
C:/projects/spec/core/io/popen_spec.rb:75:in `block (2 levels) in <top (required)>'
C:/projects/spec/core/io/popen_spec.rb:31:in `<top (required)>'
```
Not sure why this return value is behaving differently.
 
```
15)
IO#write on Windows normalizes line endings in text mode FAILED
Expected C:/projects/spec/rubyspec_temp/1292-io_write.txt
to have data "a\nb\nc"
but starts with "a\r\r\nb"
 
C:/projects/spec/core/io/write_spec.rb:155:in `block (3 levels) in <top (required)>'
C:/projects/spec/core/io/write_spec.rb:141:in `block in <top (required)>'
C:/projects/spec/core/io/write_spec.rb:140:in `<top (required)>'
```
2 "\r" ?? Bug in the spec, MRI or both? 

```
16)
Kernel#system runs commands starting with any number of @ using shell FAILED
Expected true
 to equal nil
 
C:/projects/spec/core/kernel/system_spec.rb:67:in `block (3 levels) in <top (required)>'
C:/projects/spec/core/kernel/system_spec.rb:74:in `<top (required)>'
 
17)
Kernel.system runs commands starting with any number of @ using shell FAILED
Expected true
 to equal nil
 
C:/projects/spec/core/kernel/system_spec.rb:67:in `block (3 levels) in <top (required)>'
C:/projects/spec/core/kernel/system_spec.rb:82:in `<top (required)>'
```
These use to pass with just `@object.system('does_not_exist').should == nil` but then some error is reported in the command line. Can we avoid this error in the output?
 
```
18)
Resolv#getaddress resolves localhost ERROR
ArgumentError: wrong number of arguments (1 for 2)
C:/projects/spec/library/resolv/get_address_spec.rb:12:in `block (2 levels) in <top (required)>'
C:/projects/spec/library/resolv/get_address_spec.rb:4:in `<top (required)>'
 
19)
Resolv#getaddresses resolves localhost FAILED
Expected 0
 to be greater than 0
 
C:/projects/spec/library/resolv/get_addresses_spec.rb:14:in `block (2 levels) in <top (required)>'
C:/projects/spec/library/resolv/get_addresses_spec.rb:4:in `<top (required)>'
 
20)
Resolv#getname resolves 127.0.0.1 ERROR
ArgumentError: wrong number of arguments (1 for 2)
C:/projects/spec/library/resolv/get_name_spec.rb:9:in `block (2 levels) in <top (required)>'
C:/projects/spec/library/resolv/get_name_spec.rb:3:in `<top (required)>'
 
21)
Resolv#getnames resolves 127.0.0.1 FAILED
Expected 0
 to be greater than 0
 
C:/projects/spec/library/resolv/get_names_spec.rb:13:in `block (2 levels) in <top (required)>'
C:/projects/spec/library/resolv/get_names_spec.rb:3:in `<top (required)>'

22)
Socket#getaddrinfo gets the address information FAILED
No behavior expectation was found in the example
C:/projects/spec/library/socket/socket/getaddrinfo_spec.rb:6:in `<top (required)>'
```
Not sure what are the difference with localhost and such on Windows.

```
23)
TCPServer.new sets SO_REUSEADDR on the resulting server FAILED
Expected 0
 not to equal 0
 
C:/projects/spec/library/socket/tcpserver/new_spec.rb:90:in `block (2 levels) in <top (required)>'
C:/projects/spec/library/socket/tcpserver/new_spec.rb:4:in `<top (required)>'
```
Is SO_REUSEADDR not set on Windows because of security issue? Is there sth similar to allow rebind on a port, or is it unneeded?

```
24)
TCPSocket#gethostbyname returns the canonical name as first value FAILED
Expected "127.0.0.1"
 to equal "appveyor-vm"
 
C:/projects/spec/library/socket/tcpsocket/gethostbyname_spec.rb:34:in `block (3 levels) in <top (required)>'
C:/projects/spec/library/socket/tcpsocket/gethostbyname_spec.rb:5:in `<top (required)>'
```
`localhost` issue again it seems.

**Comment by nobu** [comment]
* `File.chown` does nothing but success, for *any arguments*.
* File permissions other than "user" do not make sense and *always* equal to the "user"'s.

**Comment by eregon** [comment]
@nobu Thanks, that fixed the `chown` case.
Permissions seem to behave differently on Windows, even when considering only the users', it would seems File.open(existing_file, mode) actually changes permissions while it does not on other platforms.

**Comment by eregon** [comment]
Only 4 remaining issues: https://ci.appveyor.com/project/eregon/spec/build/185

**Comment by eregon** [comment]
And here is the first green build on AppVeyor! https://ci.appveyor.com/project/eregon/spec/build/217

**Comment by vais** [comment]
@eregon great job, congratulations!!
