### ISSUE TITLE
req.get( uri ) abends with file:/.....

### ISSUE THREAD

**Issue by hedgehog** [ruby/spec#373]
Is there an expectation that the following should work?

````ruby
begin
  require 'uri'
  require 'net/http'
  p ::File.exist?('/tmp/tomcat-8/v8.0.39/bin/apache-tomcat-8.0.39.tar.gz.md5')
  uri = URI( 'file:/tmp/tomcat-8/v8.0.39/bin/apache-tomcat-8.0.39.tar.gz.md5' )
  req= Net::HTTP.new(uri.host, uri.port)
  req.get( uri )
rescue => e
  p e.inspect
  p e.backtrace
end
````
Currently on `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]` it results in:
````ruby
true
"#<TypeError: can't dup NilClass>"
["/opt/chef/embedded/lib/ruby/2.3.0/net/http/generic_request.rb:18:in `dup'",
"/opt/chef/embedded/lib/ruby/2.3.0/net/http/generic_request.rb:18:in `initialize'",
"/opt/chef/embedded/lib/ruby/2.3.0/net/http/request.rb:15:in `initialize'",
"/opt/chef/embedded/lib/ruby/2.3.0/net/http.rb:1156:in `new'",
"/opt/chef/embedded/lib/ruby/2.3.0/net/http.rb:1156:in `get'",
"/tmp/issue.rb:7:in `<main>'"]
````

**Comment by eregon** [comment]
@hedgehog You need one `/` for the protocol, and then another one for the root of the filesystem:
```ruby
  uri = URI( 'file://tmp/tomcat-8/v8.0.39/bin/apache-tomcat-8.0.39.tar.gz.md5' )
```
Then it fails in a different way:
```
NoMethodError: undefined method `request_uri' for #<URI::Generic file://tmp/tomcat-8/v8.0.39/bin/apache-tomcat-8.0.39.tar.gz.md5>
from .../ruby-2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:19:in `initialize'
```
So I don't think this is currently supported.

You could use `open-uri` to open both local files and URLs: http://www.rubydoc.info/stdlib/open-uri/OpenURI
You need to require `open-uri` and not use the `file:/` prefix.

All that said, if you want to request a feature or bug, the right place is https://bugs.ruby-lang.org/, this tracker is for issues related to the specs themselves.
