### ISSUE TITLE
spinner runner aborts when an empty directory is given

### ISSUE THREAD

**Issue by nobu** [ruby/spec#459]
```
$ mkdir empty_dir
$ ruby spec/mspec/bin/mspec-run -B spec/default.mspec empty_dir
ruby 2.5.0dev (2017-08-02 trunk 59463) [universal.x86_64-darwin15]
Traceback (most recent call last):
	10: from spec/mspec/bin/mspec-run:7:in `<main>'
	 9: from spec/mspec/lib/mspec/utils/script.rb:265:in `main'
	 8: from spec/mspec/lib/mspec/commands/mspec-run.rb:83:in `run'
	 7: from spec/mspec/lib/mspec/runner/mspec.rb:51:in `process'
	 6: from spec/mspec/lib/mspec/runner/mspec.rb:96:in `actions'
	 5: from spec/mspec/lib/mspec/runner/mspec.rb:96:in `each'
	 4: from spec/mspec/lib/mspec/runner/mspec.rb:96:in `block in actions'
	 3: from spec/mspec/lib/mspec/runner/formatters/spinner.rb:84:in `start'
	 2: from spec/mspec/lib/mspec/runner/formatters/spinner.rb:62:in `compute_progress'
	 1: from spec/mspec/lib/mspec/runner/formatters/spinner.rb:54:in `compute_percentage'
spec/mspec/lib/mspec/runner/formatters/spinner.rb:54:in `/': divided by 0 (ZeroDivisionError)
```

`MSpecScript#entries` returns an empty array if `partial` is a directory name which has no spec files.
I'm uncertain where and how it should be dealt with.

1. abort in `MSpecScript#files` or `MSpecScript#files_from_patterns` when the list is empty.
2. same in `MSpec.register_files`.
3. same or ignore in `MSpec.process`.

**Comment by nobu** [comment]
4. abort if no files matched in `MSpecScript#entries`.

```diff
3cf0b6c56e70d89cd20071a7ad591f99dbad4c75
Author: Nobuyoshi Nakada <nobu@ruby-lang.org>
Date:   Thu Aug 3 10:19:08 2017

    script.rb: skip empty directories
    
    * spec/mspec/lib/mspec/utils/script.rb (entries): skip empty
      directories so that at least one file would run.

1 file changed, 2 insertions(+), 1 deletion(-)
 spec/mspec/lib/mspec/utils/script.rb | 3 ++-

	Modified   spec/mspec/lib/mspec/utils/script.rb
diff --git a/spec/mspec/lib/mspec/utils/script.rb b/spec/mspec/lib/mspec/utils/script.rb
index 146e3367af..3ce3b2fd3b 100644
--- a/spec/mspec/lib/mspec/utils/script.rb
+++ b/spec/mspec/lib/mspec/utils/script.rb
@@ -188,7 +188,8 @@
       if File.file?(expanded) && expanded.end_with?('.rb')
         return [expanded]
       elsif File.directory?(expanded)
-        return Dir["#{expanded}/**/*_spec.rb"].sort
+        specs = Dir["#{expanded}/**/*_spec.rb"]
+        return specs.sort unless specs.empty?
       end
     end
 
```

**Comment by eregon** [comment]
Thank you for the bug report! I'll have a look this week.
Indeed if the set of files is empty it's OK to abort mspec, I think such a check already exists somewhere.

**Comment by eregon** [comment]
I applied your patch for `MSpecScript#entries`, thank you!
