### ISSUE TITLE
File time specs depend on Linux-specific stat command

### ISSUE THREAD

**Issue by headius** [ruby/spec#785]
The File time specs (atime, ctime, mtime) do not currently pass on Windows because they depend Linux-specific output of the "stat" command.

I believe this commit enabled these specs.

https://github.com/ruby/spec/commit/55cbf498a39a1086ca453e6137de5bf6d53bfda6

I suspect they are being run in CI against an environment that has installed additional unix tools, probably from whatever build harness is being used to build Ruby itself. This requirement does not appear to be documented anywhere. The same failures occur for the same reasons on JRuby on Windows.

I believe these specs should be modified to either not run or not use the "stat" command on Windows.

The failures are below:

```
1)
File.atime returns the last access time for the named file with microseconds ERROR
Errno::ENOENT: No such file or directory - stat -c%x 'C:/Users/headius/work/jruby/spec/ruby/core/file/atime_spec.rb'
C:/Users/headius/work/jruby/spec/ruby/core/file/atime_spec.rb:21:in ``'
C:/Users/headius/work/jruby/spec/ruby/core/file/atime_spec.rb:21:in `block (3 levels) in <top (required)>'
C:/Users/headius/work/jruby/spec/ruby/core/file/atime_spec.rb:3:in `<top (required)>'

2)
File.ctime returns the change time for the named file (the time at which directory information about the file was changed, not the file itself) with microseconds. ERROR
Errno::ENOENT: No such file or directory - stat -c%z 'C:/Users/headius/work/jruby/spec/ruby/core/file/ctime_spec.rb'
C:/Users/headius/work/jruby/spec/ruby/core/file/ctime_spec.rb:19:in ``'
C:/Users/headius/work/jruby/spec/ruby/core/file/ctime_spec.rb:19:in `block (3 levels) in <top (required)>'
C:/Users/headius/work/jruby/spec/ruby/core/file/ctime_spec.rb:3:in `<top (required)>'

3)
File.mtime returns the modification Time of the file with microseconds ERROR
Errno::ENOENT: No such file or directory - stat -c%y 'C:/Users/headius/work/jruby/spec/ruby/core/file/mtime_spec.rb'
C:/Users/headius/work/jruby/spec/ruby/core/file/mtime_spec.rb:20:in ``'
C:/Users/headius/work/jruby/spec/ruby/core/file/mtime_spec.rb:20:in `block (3 levels) in <top (required)>'
C:/Users/headius/work/jruby/spec/ruby/core/file/mtime_spec.rb:3:in `<top (required)>'
```

**Comment by eregon** [comment]
Is there an alternative CLI tool that gives those times on Windows?

It seems most CIs have `stat` as this is the first report about it.
So I think documenting it might be a good way.
There are a few other CLI tools specs depend on like `which` and `find`.
Which CI do you run on BTW?

cc @MSP-Greg

**Comment by MSP-Greg** [comment]
@headius

> I suspect they are being run in CI against an environment that has installed additional unix tools

Please feel free to search thru all the test suites of Ruby and/or popular gems that call *nix utilities via a shell or command line and use the result for comparison with results of the tested code.  I've been busy with other things, so I haven't taken the time to translate them to Windows PowerShell/Command script.

Because of that, enabling the MSYS2 tools is common in CI.  The tools have been available in AppVeyor and Actions for quite a while.  If you'd like help installing them on a local system, I'd be happy to help.  MSYS2 uses pacman once installed...
